### PR TITLE
Fix most PSScriptAnalyzer issues

### PR DESCRIPTION
**Pull request by mhendric**
#### Pull Request (PR) description
Fixes most PSScriptAnalyzer issues for the module. Note that I'm unsure why the 3 .psm1 files are showing in GitHub that the whole file was changed. I suspect that this has to do with a recent change to .gitattributes, but am not positive. Looks like they show up correctly in Reviewable though.

PSScriptAnalyzer Before:
```
Count Name
----- ----
   18 PSPossibleIncorrectComparisonWithNull
    8 PSDSCUseVerboseMessageInDSCResource
    6 PSUseDeclaredVarsMoreThanAssignments
    4 PSAvoidTrailingWhitespace
    3 PSUseToExportFieldsInManifest
    3 PSDSCDscExamplesPresent
    3 PSUseShouldProcessForStateChangingFunctions
    2 PSAvoidUsingWriteHost
    2 PSAvoidGlobalVars
    2 PSDSCDscTestsPresent
    2 PSAvoidUsingCmdletAliases
```

PSScriptAnalyzer After:
```
Count Name
----- ----
    3 PSUseShouldProcessForStateChangingFunctions
    3 PSDSCDscExamplesPresent
    3 PSUseToExportFieldsInManifest
    2 PSDSCDscTestsPresent
```

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/27)

### CODE REVIEW

**Comment by mhendric** [comment]
FYI, I'm done pushing changes on this one. This should be ready for review when someone gets to it. Thanks!

**Review by athaynes — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/27)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @athaynes and @mhendric)

___
*[README.md, line 115 at r1](https://reviewable.io/reviews/powershell/xbitlocker/27#-LQePFgz1jmSGB5jo_0C:-LQePFh-BKFfX8tx4gLz:b-usjzp8) ([raw file](https://github.com/powershell/xbitlocker/blob/635a3ee161ba912f091ee3fc77f7a9f3b9bd083b/README.md#L115)):*
> ```Markdown
> 
> *   *Identity:Not actually used, so could be anything
> *   AllowClear:Indicates that the provisioning process clears the TPM, if necessary, to move the TPM closer to complying with Windows Server? 2012 standards
> ```

why the question mark?
___
*[DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1, line 368 at r1](https://reviewable.io/reviews/powershell/xbitlocker/27#-LQeQ8p77ASzWhR3xKu4:-LQeQ8p77ASzWhR3xKu5:b-f84r8u) ([raw file](https://github.com/powershell/xbitlocker/blob/635a3ee161ba912f091ee3fc77f7a9f3b9bd083b/DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1#L368)):*
> ```PowerShell
> 
>     #First get all Bitlocker Volumes of type Data
>     $allBlvs = Get-BitLockerVolume | Where-Object -FilterScript {$_.VolumeType -eq "Data"}
> ```

Not really an issue, but if you don't have a variable, you don't need double quotes.  
___
*[Test/Test-xBitlocker.ps1, line 104 at r1](https://reviewable.io/reviews/powershell/xbitlocker/27#-LQeRb53E0ZZmXXgF3eR:-LQeRb53E0ZZmXXgF3eS:b-kgblwf) ([raw file](https://github.com/powershell/xbitlocker/blob/635a3ee161ba912f091ee3fc77f7a9f3b9bd083b/Test/Test-xBitlocker.ps1#L104)):*
> ```PowerShell
> function RunTest
> {
>     param([string]$TestName, [string[]]$ModulesToImport, [Hashtable]$Parameters)
> ```

This function does not conform to style guides. This is my first time to look at this module, but do the standard test templates not work for this module?

**Review by mhendric — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/27)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @athaynes)

___
*[README.md, line 115 at r1](https://reviewable.io/reviews/powershell/xbitlocker/27#-LQePFgz1jmSGB5jo_0C:-LQeXt1NAK3hR79ff9c3:b-dal0jb) ([raw file](https://github.com/powershell/xbitlocker/blob/635a3ee161ba912f091ee3fc77f7a9f3b9bd083b/README.md#L115)):*
<details><summary><i>Previously, athaynes (Adam Haynes) wrote…</i></summary><blockquote>

why the question mark?
</blockquote></details>

This was originally a 'Registered Trademark' symbol, but running the metafixer ConvertTo-ASCII seems to have changed it to a ?. It's probably best to have neither. I will drop it entirely.
___
*[DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1, line 368 at r1](https://reviewable.io/reviews/powershell/xbitlocker/27#-LQeQ8p77ASzWhR3xKu4:-LQeYXRd4uAe1ZXZsEnF:bw17c69) ([raw file](https://github.com/powershell/xbitlocker/blob/635a3ee161ba912f091ee3fc77f7a9f3b9bd083b/DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1#L368)):*
<details><summary><i>Previously, athaynes (Adam Haynes) wrote…</i></summary><blockquote>

Not really an issue, but if you don't have a variable, you don't need double quotes.  
</blockquote></details>

This line wasn't actually changed for this PR, but I agree, Double Quotes aren't necessary here, and go against the DSC style guidelines. At some point this will need to be fixed as part of an effort to make this a High Quality Resource Module, but I will leave that for another PR. I'll open an Issue to track this.
___
*[Test/Test-xBitlocker.ps1, line 104 at r1](https://reviewable.io/reviews/powershell/xbitlocker/27#-LQeRb53E0ZZmXXgF3eR:-LQeYqkNDi6_-oaVghEu:b-x9lkcr) ([raw file](https://github.com/powershell/xbitlocker/blob/635a3ee161ba912f091ee3fc77f7a9f3b9bd083b/Test/Test-xBitlocker.ps1#L104)):*
<details><summary><i>Previously, athaynes (Adam Haynes) wrote…</i></summary><blockquote>

This function does not conform to style guides. This is my first time to look at this module, but do the standard test templates not work for this module?
</blockquote></details>

This is the original integration test file which was created well before this module went open source. The file should probably be removed entirely once similar Integration or Unit tests have been added. I'll open an Issue to track getting everything in this file moved to appropriate templates.

**Review by mhendric — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/27)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @athaynes)

___
*[README.md, line 115 at r1](https://reviewable.io/reviews/powershell/xbitlocker/27#-LQePFgz1jmSGB5jo_0C:-LQe_OZiCTUPzQiM4lJR:b-896fix) ([raw file](https://github.com/powershell/xbitlocker/blob/635a3ee161ba912f091ee3fc77f7a9f3b9bd083b/README.md#L115)):*
<details><summary><i>Previously, mhendric (Mike Hendrickson) wrote…</i></summary><blockquote>

This was originally a 'Registered Trademark' symbol, but running the metafixer ConvertTo-ASCII seems to have changed it to a ?. It's probably best to have neither. I will drop it entirely.
</blockquote></details>

Done.

**Review by athaynes — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/27)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
