### PR TITLE
Fixes for issues #10 and #11

### LINKED ISSUE #10: AutoBitLocker resource does not encrypt volumes with drive letter assigned
Function GetAutoBitLockerStatus in MSFT_xBLAutoBitlocker.psm1 uses `$allBlvs = Get-BitLockerVolume | where {$_.VolumeType -eq "Data"}` at line 365 to get list of Data volumes and
`Get-Volume -Path $blv.MountPoint` to filter Fixed vs Removable at line 381. This works fine for volumes without drive letter assigned (mountpoint returned by `Get-BitlockerVolume` is `\\?\Volume{<guid>}\`

But for volumes with drive letter assigned, `Get-Volume -Path` does not work. In that case, it is necessary to use `Get-Volume -DriveLetter` instead.

### LINKED ISSUE #11: AutoBitLocker resource incorrectly identifies Fixed vs Removable drives
Current implementation of AutoBitLocker resource uses `Get-Volume` to differentiate between Fixed and Removable drives. This does not work correctly as there are drives reported as Fixed, yet Bitlocker evaluates them as Removable and therefore applies different GPO settings to them. I saw this for certain HP SAS controllers, VMware can also behave this way (https://kb.vmware.com/s/article/1012225) - seems to be related to the way storage controller reports disk capabilities to the OS.

Instead of using `Get-Volume`, I found `\root\cimv2\security\microsoftvolumeencryption:Win32_EncryptableVolume.VolumeType` property to correctly report volume types as evaluated by Bitlocker:
0 - OS volume
1 - Fixed volume
2 - Removable volume

### PR DESCRIPTION
**Pull request by MartinVokurek**
Fixes #10 
Fixes #11

This change is [Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/14)

### CODE REVIEW

**Comment by johlju** [comment]
Awesome work here! Thank you!

I merged updates to this resource module so if you rebase the common tests should pass.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/powershell/xbitlocker/14#-LD_edTK7F8B9NvTrYKl:-LD_edTK7F8B9NvTrYKm:bcxpg64) (no related file):*
Would you be up to creating a unit tests, for at least the changes in this PR? I added a template in the Tests/Unit folder.

---

*[DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1, line 380 at r1](https://reviewable.io/reviews/powershell/xbitlocker/14#-LD_fdkc94B61-GnDiRW:-LD_fdkc94B61-GnDiRX:bq3z3k3) ([raw file](https://github.com/powershell/xbitlocker/blob/be4bc465cb3415e1e03801b1af79281349bff880/DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1#L380)):*
> ```
> $blDriveType
> ```

We should avoid abbreviations. Could we maybe call this `$DriveTypeValue` or similar (not sure of the best naming here) so that it' more clear that it contain the numeric value of the volume type.

---

*[DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1, line 388 at r1](https://reviewable.io/reviews/powershell/xbitlocker/14#-LD_hZZ9Cb3P91lZiTWE:-LD_hZZ9Cb3P91lZiTWF:b-jy1hx1) ([raw file](https://github.com/powershell/xbitlocker/blob/be4bc465cb3415e1e03801b1af79281349bff880/DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1#L388)):*
> ```PowerShell
>             $vol = $null
>             
>             if (Split-Path -Path $blv.MountPoint -IsAbsolute) {
> ```

We should have open and closing braces on separate rows.

---

*[DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1, line 390 at r1](https://reviewable.io/reviews/powershell/xbitlocker/14#-LD_fCuW1w4mS_y2MBF7:-LD_fCuW1w4mS_y2MBF8:b5o0tew) ([raw file](https://github.com/powershell/xbitlocker/blob/be4bc465cb3415e1e03801b1af79281349bff880/DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1#L390)):*
> ```
> Get-WmiObject
> ```

Please use Get-CimInstance instead.
https://ci.appveyor.com/project/PowerShell/xbitlocker/build/1.1.37.0#L1097

---

*[DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1, line 390 at r1](https://reviewable.io/reviews/powershell/xbitlocker/14#-LD_i7wYEUDRqSalkA-D:-LD_grqJ37mVguqWOrXm:btmj7gr) ([raw file](https://github.com/powershell/xbitlocker/blob/be4bc465cb3415e1e03801b1af79281349bff880/DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1#L390)):*
> ```PowerShell
>             if (Split-Path -Path $blv.MountPoint -IsAbsolute) {
>                 # MountPoint is a Drive Letter
>                 $vol = Get-WmiObject -Namespace "root\cimv2\security\microsoftvolumeencryption" -Class Win32_Encryptablevolume -ErrorAction SilentlyContinue | Where-Object {($_.DriveLetter -eq $blv.Mountpoint) -and ($_.VolumeType -eq $blDriveType)}
> ```

The difference here is the `Where-Object`. Maybe we could call Get-CimInstance once, before the if-block, and the evaluate the result using `Where-Object` depending if it is a absolute path or not?

---

*[DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1, line 391 at r1](https://reviewable.io/reviews/powershell/xbitlocker/14#-LD_he61DfHdF-EnmwDQ:-LD_he61DfHdF-EnmwDR:b38qzv3) ([raw file](https://github.com/powershell/xbitlocker/blob/be4bc465cb3415e1e03801b1af79281349bff880/DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1#L391)):*
> ```PowerShell
>                 # MountPoint is a Drive Letter
>                 $vol = Get-WmiObject -Namespace "root\cimv2\security\microsoftvolumeencryption" -Class Win32_Encryptablevolume -ErrorAction SilentlyContinue | Where-Object {($_.DriveLetter -eq $blv.Mountpoint) -and ($_.VolumeType -eq $blDriveType)}
>             } else {
> ```

We should have open and closing braces on seperate rows.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/14#-:-LD_im9f-4TbSaCkZnwx:b-j6tsnd)*

**Comment by johlju** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[README.md, line 105 at r1](https://reviewable.io/reviews/powershell/xbitlocker/14#-LD_oLP988wWteS-zSKW:-LD_oLP988wWteS-zSKX:b-71qv87) ([raw file](https://github.com/powershell/xbitlocker/blob/be4bc465cb3415e1e03801b1af79281349bff880/README.md#L105)):*
> ```Markdown
> ### Unreleased
> * Converted appveyor.yml to install Pester from PSGallery instead of from Chocolatey.
> * Fixed issue which caused xBLAutoBitlocker to incorrectly detect Fixed vs Removable volumes
> ```

If an entry resolves an issue please reference the issue where applicable. You may suffix (it's optional) each entry with your name. Example of the format for the entry.
```
* Descriptive entry ([issue #123](https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/123). [Name/Alias (@github_account)](https://github.com/github_account)`
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/14)*

**Comment by johlju** [comment]
When you have resolved the review comments, or if you need to discuss a comment. Could you please go into Reviewable and write 'Done' (or click the done-button) on each of the review comments. This allows me to acknowledge (resolve) the review comments and I know that you are done with each change. After you written 'Done' on each review comment,  or comment on the review comment if it needs further discussion, then click the big green 'Publish' button on top of the page. That will send all your comments back as one big comment to this PR.
You find Reviewable if you click on the big purple Reviewable-button in the PR description.

**Comment by MartinVokurek** [comment]
Review status: 0 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/powershell/xbitlocker/14#-LD_edTK7F8B9NvTrYKl:-LDezYqG8Qj8pCgP0x5x:bf9o5aq) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Would you be up to creating a unit tests, for at least the changes in this PR? I added a template in the Tests/Unit folder.
</blockquote></details>

I am not very fluent with Pester, I used it only handful of times for my experiments. I can try (have to learn it sooner or later anyway), but it's gonna be slow and probably lot of trial-and-failure

---

*[README.md, line 105 at r1](https://reviewable.io/reviews/powershell/xbitlocker/14#-LD_oLP988wWteS-zSKW:-LDf06I00aog9RFzSopn:b-896fix) ([raw file](https://github.com/powershell/xbitlocker/blob/be4bc465cb3415e1e03801b1af79281349bff880/README.md#L105)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

If an entry resolves an issue please reference the issue where applicable. You may suffix (it's optional) each entry with your name. Example of the format for the entry.
```
* Descriptive entry ([issue #123](https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/123). [Name/Alias (@github_account)](https://github.com/github_account)`
```

</blockquote></details>

Done.

---

*[DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1, line 380 at r1](https://reviewable.io/reviews/powershell/xbitlocker/14#-LD_fdkc94B61-GnDiRW:-LDf9pK76Nl14hiO2d7H:b-896fix) ([raw file](https://github.com/powershell/xbitlocker/blob/be4bc465cb3415e1e03801b1af79281349bff880/DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1#L380)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $blDriveType
> ```

We should avoid abbreviations. Could we maybe call this `$DriveTypeValue` or similar (not sure of the best naming here) so that it' more clear that it contain the numeric value of the volume type.
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1, line 388 at r1](https://reviewable.io/reviews/powershell/xbitlocker/14#-LD_hZZ9Cb3P91lZiTWE:-LDf9r4j6ojhheNm1hEu:b-896fix) ([raw file](https://github.com/powershell/xbitlocker/blob/be4bc465cb3415e1e03801b1af79281349bff880/DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1#L388)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should have open and closing braces on separate rows.
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1, line 390 at r1](https://reviewable.io/reviews/powershell/xbitlocker/14#-LD_fCuW1w4mS_y2MBF7:-LDf1v8sDB7JFd8Tkh6N:b-896fix) ([raw file](https://github.com/powershell/xbitlocker/blob/be4bc465cb3415e1e03801b1af79281349bff880/DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1#L390)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Get-WmiObject
> ```

Please use Get-CimInstance instead.
https://ci.appveyor.com/project/PowerShell/xbitlocker/build/1.1.37.0#L1097

</blockquote></details>

Done.

---

*[DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1, line 390 at r1](https://reviewable.io/reviews/powershell/xbitlocker/14#-LD_i7wYEUDRqSalkA-D:-LDf1ytf8GsrY-nCNRE5:b-rhptt3) ([raw file](https://github.com/powershell/xbitlocker/blob/be4bc465cb3415e1e03801b1af79281349bff880/DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1#L390)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

The difference here is the `Where-Object`. Maybe we could call Get-CimInstance once, before the if-block, and the evaluate the result using `Where-Object` depending if it is a absolute path or not?
</blockquote></details>

Done.

Out of curiosity and for my education: what's the difference? This is in IF-ELSE so GET-CIMINSTANCE does not get called twice anyway.

---

*[DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1, line 391 at r1](https://reviewable.io/reviews/powershell/xbitlocker/14#-LD_he61DfHdF-EnmwDQ:-LDf9u7S1h06kKFDAdz4:b-896fix) ([raw file](https://github.com/powershell/xbitlocker/blob/be4bc465cb3415e1e03801b1af79281349bff880/DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1#L391)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should have open and closing braces on seperate rows.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/14)*

**Comment by johlju** [comment]
@MartinVokurek seems this PR are changing more files than it should. Maybe the rebase didn't work correctly? There are a commit from me, see https://github.com/PowerShell/xBitlocker/pull/14/commits.

Could you pleas try the rebase again? See here for help (same as resolving conflicts) https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts

**Comment by johlju** [comment]
Review status: 1 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/powershell/xbitlocker/14#-LD_edTK7F8B9NvTrYKl:-LDqmjxr1qj464pu-Qpv:bz7nqom) (no related file):*
<details><summary><i>Previously, MartinVokurek (Martin Vokurek) wrote…</i></summary><blockquote>

I am not very fluent with Pester, I used it only handful of times for my experiments. I can try (have to learn it sooner or later anyway), but it's gonna be slow and probably lot of trial-and-failure
</blockquote></details>

Then this is a good opportunity to learn! Happy to give pointers, and if you get stuck on errors I will help you solve them. :slightly_smiling_face: 

---

*[DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1, line 390 at r1](https://reviewable.io/reviews/powershell/xbitlocker/14#-LD_i7wYEUDRqSalkA-D:-LDqnPx-6k_oyiw04yA4:b-gwp8mx) ([raw file](https://github.com/powershell/xbitlocker/blob/be4bc465cb3415e1e03801b1af79281349bff880/DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1#L390)):*
<details><summary><i>Previously, MartinVokurek (Martin Vokurek) wrote…</i></summary><blockquote>

Done.

Out of curiosity and for my education: what's the difference? This is in IF-ELSE so GET-CIMINSTANCE does not get called twice anyway.
</blockquote></details>

No problem, happy to explain. It's basically to reduce duplicated code where we can. If we someday need to change the Get-CimInstance call, we only have to change it at one location, reducing that someone forgets to change the second call (or third or forth location if it were to be used more). 

For example, we could also have move up the `($_.VolumeType -eq $DriveTypeValue)` to the Get-CimInstance call. But that might be to excessive, we don't have to go overboard with it either. :slightly_smiling_face: 

```
| Where-Object {
    $_.VolumeType -eq $DriveTypeValue
}
``

No need to don anything more with this. This looks good as-is.
```


---

*[DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1, line 381 at r3](https://reviewable.io/reviews/powershell/xbitlocker/14#-LDqpqTV2qlxOANi2U99:-LDqpqTV2qlxOANi2U9A:b-x6moiq) ([raw file](https://github.com/powershell/xbitlocker/blob/504dd6d7d0d5a835c878c1828b56e6e3db2ee904/DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1#L381)):*
> ```PowerShell
>         switch ($DriveType)
>         {
>             "Fixed"
> ```

We should use single-quotes where applicable. Throughout.

---

*[DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1, line 383 at r3](https://reviewable.io/reviews/powershell/xbitlocker/14#-LDqp_pU9JCGSR7jHRDo:-LDqp_pU9JCGSR7jHRDp:bjh7pin) ([raw file](https://github.com/powershell/xbitlocker/blob/504dd6d7d0d5a835c878c1828b56e6e3db2ee904/DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1#L383)):*
> ```
> $DriveTypeValue
> ```

We should change this to `$driveTypeValue` (I wrote it wrong in previous comment). We should use camelCase on local variables (parameters use PascalCase). Throughout.

---

*[DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1, line 395 at r3](https://reviewable.io/reviews/powershell/xbitlocker/14#-LDqougY3W79SB2Kr1eE:-LDqougY3W79SB2Kr1eF:b5t8liv) ([raw file](https://github.com/powershell/xbitlocker/blob/504dd6d7d0d5a835c878c1828b56e6e3db2ee904/DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1#L395)):*
> ```
> $EncryptableVolumes
> ```


We should change this to `$encryptableVolumes`. We should use camelCase on local variables (parameters use PascalCase). Throughout.

---

*[DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1, line 395 at r3](https://reviewable.io/reviews/powershell/xbitlocker/14#-LDqqO7XCIe8Mo65xy5m:-LDqqO7XCIe8Mo65xy5n:b4xdky0) ([raw file](https://github.com/powershell/xbitlocker/blob/504dd6d7d0d5a835c878c1828b56e6e3db2ee904/DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1#L395)):*
> ```
> $EncryptableVolumes=Get-CimInstance
> ```

Please add spaces around the equal sign.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/14)*

**Comment by MartinVokurek** [comment]
I tried another rebase, but I think it's not getting any better. It's just two files, maybe it would be the easiest for me to drop the whole branch and start again fresh?

---

Review status: 1 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1, line 381 at r3](https://reviewable.io/reviews/powershell/xbitlocker/14#-LDqpqTV2qlxOANi2U99:-LDqyJU80hqZ2XFI7fRH:b-896fix) ([raw file](https://github.com/powershell/xbitlocker/blob/099b79c6c59c278eda3567f00bd8fc26205e1570/DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1#L381)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should use single-quotes where applicable. Throughout.
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1, line 383 at r3](https://reviewable.io/reviews/powershell/xbitlocker/14#-LDqp_pU9JCGSR7jHRDo:-LDqydVn6_kuIQ-Xw20_:b-896fix) ([raw file](https://github.com/powershell/xbitlocker/blob/099b79c6c59c278eda3567f00bd8fc26205e1570/DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1#L383)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $DriveTypeValue
> ```

We should change this to `$driveTypeValue` (I wrote it wrong in previous comment). We should use camelCase on local variables (parameters use PascalCase). Throughout.
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1, line 395 at r3](https://reviewable.io/reviews/powershell/xbitlocker/14#-LDqougY3W79SB2Kr1eE:-LDqyWwJBqBpiosSw8Uy:b-896fix) ([raw file](https://github.com/powershell/xbitlocker/blob/099b79c6c59c278eda3567f00bd8fc26205e1570/DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1#L395)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $EncryptableVolumes
> ```


We should change this to `$encryptableVolumes`. We should use camelCase on local variables (parameters use PascalCase). Throughout.
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1, line 395 at r3](https://reviewable.io/reviews/powershell/xbitlocker/14#-LDqqO7XCIe8Mo65xy5m:-LDqyk4JCnu4zTG0cH5Z:brra16q) ([raw file](https://github.com/powershell/xbitlocker/blob/099b79c6c59c278eda3567f00bd8fc26205e1570/DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1#L395)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $EncryptableVolumes=Get-CimInstance
> ```

Please add spaces around the equal sign.
</blockquote></details>

Done.

Gosh, I am no developer, if I have to try to remember all these nuances, my willingness to fix anything will quickly return back to zero :-)

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/14#-:-LDqv89F-tHSBrnl8RwH:bx8hc0)*

**Comment by johlju** [comment]
Yes, if the rebase didn't work, I think that would be the quickest to create a new branch and open a new PR. :slightly_smiling_face: 

---

Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1, line 395 at r3](https://reviewable.io/reviews/powershell/xbitlocker/14#-LDqqO7XCIe8Mo65xy5m:-LDr0Cuz8EzMNjgEZ5PL:b-yxo2ta) ([raw file](https://github.com/powershell/xbitlocker/blob/099b79c6c59c278eda3567f00bd8fc26205e1570/DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1#L395)):*
<details><summary><i>Previously, MartinVokurek (Martin Vokurek) wrote…</i></summary><blockquote>

Done.

Gosh, I am no developer, if I have to try to remember all these nuances, my willingness to fix anything will quickly return back to zero :-)
</blockquote></details>

You are doing great! That's part whats the reviews are for, helping with this. :slightly_smiling_face: 

Style guidelines are not easier for developers either. :slightly_smiling_face:  I think being an IT Pro (engineer or developer) coding PowerShell is much the same.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/14#-:-LDr-tev4rFVK0J1xkKE:b-kmcy4d)*

**Comment by MartinVokurek** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1, line 395 at r3](https://reviewable.io/reviews/powershell/xbitlocker/14#-LDqqO7XCIe8Mo65xy5m:-LDrAaBqCLVdeU-0gdLa:bceyzu) ([raw file](https://github.com/powershell/xbitlocker/blob/099b79c6c59c278eda3567f00bd8fc26205e1570/DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1#L395)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

You are doing great! That's part whats the reviews are for, helping with this. :slightly_smiling_face: 

Style guidelines are not easier for developers either. :slightly_smiling_face:  I think being an IT Pro (engineer or developer) coding PowerShell is much the same.
</blockquote></details>

Yeah, but for my Support Engineer persona, the magic of Powershell is that you can do something "fast" and not bother about code beauty :)

Ok, I'll switch to another branch, try to build some small tests and create another PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/14)*

**Comment by MartinVokurek** [comment]
Closing after failed rebase, will open another PR with new branch

**Pull request closed without merging**
