### PR TITLE
MSFT_xBLTpm: Add Unit Tests for xBLTpm

### PR DESCRIPTION
**Pull request by mhendric**
#### Pull Request (PR) description
Adds Unit Tests for xBLTpm

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/34)

### CODE REVIEW

**Comment by mhendric** [comment]
Reaching out to the xBitlocker and Git community. Can someone please perform a code review on this? I don't want to merge until another set of eyes have been on this. Thanks!

**Comment by mhendric** [comment]
Reaching out to recent contributors. @johlju, @kwirkykat, @MartinVokurek, @J0F3, would one of you be able to review this PR? Thanks.

**Review by J0F3 — COMMENTED** [review]
LGTM

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/34#-:-LRkNOI-CfjTbr3rw8AE:bb6ywmx)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mhendric** [comment]
Thanks for the review @J0F3 !

**Pull request merged**
