### PR TITLE
Fix attempt for #13

### LINKED ISSUE #13: 'Test' pass incorrectly returns $True for decrypted volumes, causing the volume to be skipped for 'Set' pass and never encrypted
The TestBitlocker function evaluates KeyProtectors and AutoUnlock status for given volume. If they do not match, the function returns $false and "Set" is executed.
If, however, KeyProtectors are configured correctly and AutoUnlock is in desired state, yet the volume is in "FullyDecrypted" state, TestBitlocker returns $True and the volume is not processed for encryption anymore.
This can happen more likely for OS volume: the volume is attempted to be encrypted by EnableBitlocker, but call to `Enable-Bitlocker` fails for whatever reason, the resource fails as expected. But the KeyProtectors are already in place and not removed upon failure and therefore subsequent configuration runs will evaluate Test as $True and skip Set.

Repro:
Try to use xBLBitlocker to encrypt OS volume in Hyper-V VM with Dynamically Expanding disks and no UsedSpaceOnly specified (I used TPM and RecoveryPassword protectors and had "Full Encryption" set in GPO). First attempt fails with "BitLocker Drive Encryption only supports Used Space Only encryption on thin provisioned storage. (Exception from HRESULT: 0x803100A5)". Subsequent runs will skip Set and report success, yet the volume never gets encrypted.

Suggested fix:
TestBitlocker should test "VolumeStatus" of given Bitlocker volume. If the status is "FullyDecrypted", it should return $false.

### PR DESCRIPTION
**Pull request by MartinVokurek**
Fixes #13 

This change is [Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/16)

### CODE REVIEW

**Comment by johlju** [comment]
Awesome work on the tests! Thank you! Just minor comments.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[Tests/Unit/xBitlockerCommon.tests.ps1, line 1 at r1](https://reviewable.io/reviews/powershell/xbitlocker/16#-LDqR9qC72yuNk50mLTt:-LDqR9qC72yuNk50mLTu:b-yfy09y) ([raw file](https://github.com/powershell/xbitlocker/blob/7b9221386955463266f74e4d784aafd52fb37e04/Tests/Unit/xBitlockerCommon.tests.ps1#L1)):*
> ```PowerShell
> <#
> ```

Could you please 
* Delete all template comments (TODOs, etc.)
* Remove any unused BeforeAll-, AfterAll-, BeforeEach- and AfterEach-blocks.
* Remove this comment-based help.

---

*[Tests/Unit/xBitlockerCommon.tests.ps1, line 21 at r1](https://reviewable.io/reviews/powershell/xbitlocker/16#-LDqUtssC8doeZ6LTPLt:-LDqUtssC8doeZ6LTPLu:bow8su4) ([raw file](https://github.com/powershell/xbitlocker/blob/7b9221386955463266f74e4d784aafd52fb37e04/Tests/Unit/xBitlockerCommon.tests.ps1#L21)):*
> ```PowerShell
> # Unit Test Template Version: 1.2.1
> $script:moduleRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
> if ( (-not (Test-Path -Path (Join-Path -Path $script:moduleRoot -ChildPath 'DSCResource.Tests'))) -or `
> ```

Since we are testing a helper module (and not a resource), the header is not necessary, so you can just keep line 20 and remove the rest of `#region HEADER`. Basically, keep what you need to be able to run the test.

---

*[Tests/Unit/xBitlockerCommon.tests.ps1, line 30 at r1](https://reviewable.io/reviews/powershell/xbitlocker/16#-LDqRSM6DeZ6x63ujk0R:-LDqRSM6DeZ6x63ujk0S:b-scwgs0) ([raw file](https://github.com/powershell/xbitlocker/blob/7b9221386955463266f74e4d784aafd52fb37e04/Tests/Unit/xBitlockerCommon.tests.ps1#L30)):*
> ```PowerShell
> 
> # TODO: Insert the correct <ModuleName> and <ResourceName> for your resource
> #$TestEnvironment = Initialize-TestEnvironment `
> ```

You can remove this row.

---

*[Tests/Unit/xBitlockerCommon.tests.ps1, line 42 at r1](https://reviewable.io/reviews/powershell/xbitlocker/16#-LDqRbZWC8PWZx2vtfrl:-LDqRbZWC8PWZx2vtfrm:b-scwgs0) ([raw file](https://github.com/powershell/xbitlocker/blob/7b9221386955463266f74e4d784aafd52fb37e04/Tests/Unit/xBitlockerCommon.tests.ps1#L42)):*
> ```PowerShell
> 
> function Invoke-TestCleanup {
> #    Restore-TestEnvironment -TestEnvironment $TestEnvironment
> ```

You can remove this row.

---

*[Tests/Unit/xBitlockerCommon.tests.ps1, line 79 at r1](https://reviewable.io/reviews/powershell/xbitlocker/16#-LDqVjrn4Y39ph9SnYXf:-LDqVjrn4Y39ph9SnYXg:b36pi8j) ([raw file](https://github.com/powershell/xbitlocker/blob/7b9221386955463266f74e4d784aafd52fb37e04/Tests/Unit/xBitlockerCommon.tests.ps1#L79)):*
> ```PowerShell
>                     -ModuleName 'xBitlockerCommon' `
>                     -MockWith {
>                         param (
> ```

We can move the param block inside `Get-BitlockerVolume` so that you only need to specify that once.
Suggest changing to this so we align with the style guideline.

```
function Get-BitlockerVolume
{
    param
    (
        [Parameter()]
        [System.String]
        $MountPoint
    )
 }
```

---

*[Tests/Unit/xBitlockerCommon.tests.ps1, line 111 at r1](https://reviewable.io/reviews/powershell/xbitlocker/16#-LDqWJfCDFVNgNkxP4dC:-LDqWJfCDFVNgNkxP4dD:b-7a4zxa) ([raw file](https://github.com/powershell/xbitlocker/blob/7b9221386955463266f74e4d784aafd52fb37e04/Tests/Unit/xBitlockerCommon.tests.ps1#L111)):*
> ```PowerShell
>                 Mock -CommandName Get-BitlockerVolume -ModuleName 'xBitlockerCommon' -MockWith {
>                             # Encrypted with TPM and Recovery Password Key Protectors
>                             param (
> ```

Remove this, see previous comment.

---

*[Tests/Unit/xBitlockerCommon.tests.ps1, line 144 at r1](https://reviewable.io/reviews/powershell/xbitlocker/16#-LDqWMAN7eCESavsC-Ad:-LDqWMAN7eCESavsC-Ae:b-7a4zxa) ([raw file](https://github.com/powershell/xbitlocker/blob/7b9221386955463266f74e4d784aafd52fb37e04/Tests/Unit/xBitlockerCommon.tests.ps1#L144)):*
> ```PowerShell
>                     -MockWith {
>                             # Encrypted with TPM and Recovery Password Key Protectors
>                             param (
> ```

Remove this, see previous comment.

---

*[Tests/Unit/xBitlockerCommon.tests.ps1, line 176 at r1](https://reviewable.io/reviews/powershell/xbitlocker/16#-LDqUlLB4N4RhG5htuHl:-LDqRVDi0M8MEZDyeMqb:brkupgl) ([raw file](https://github.com/powershell/xbitlocker/blob/7b9221386955463266f74e4d784aafd52fb37e04/Tests/Unit/xBitlockerCommon.tests.ps1#L176)):*
> ```PowerShell
> finally
> {
> #    Invoke-TestCleanup
> ```

Please uncomment this, or remove if the function was not used. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/16#-:-LDqWuaM3t29X-ZTd9iM:b-je5qey)*

**Comment by MartinVokurek** [comment]
Review status: 2 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[Tests/Unit/xBitlockerCommon.tests.ps1, line 1 at r1](https://reviewable.io/reviews/powershell/xbitlocker/16#-LDqR9qC72yuNk50mLTt:-LDqlzMLBs-kH9RnAlGr:b-896fix) ([raw file](https://github.com/powershell/xbitlocker/blob/7b9221386955463266f74e4d784aafd52fb37e04/Tests/Unit/xBitlockerCommon.tests.ps1#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Could you please 
* Delete all template comments (TODOs, etc.)
* Remove any unused BeforeAll-, AfterAll-, BeforeEach- and AfterEach-blocks.
* Remove this comment-based help.
</blockquote></details>

Done.

---

*[Tests/Unit/xBitlockerCommon.tests.ps1, line 21 at r1](https://reviewable.io/reviews/powershell/xbitlocker/16#-LDqUtssC8doeZ6LTPLt:-LDqm2C2CeIMuiNcQ7WO:b-896fix) ([raw file](https://github.com/powershell/xbitlocker/blob/7b9221386955463266f74e4d784aafd52fb37e04/Tests/Unit/xBitlockerCommon.tests.ps1#L21)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Since we are testing a helper module (and not a resource), the header is not necessary, so you can just keep line 20 and remove the rest of `#region HEADER`. Basically, keep what you need to be able to run the test.
</blockquote></details>

Done.

---

*[Tests/Unit/xBitlockerCommon.tests.ps1, line 30 at r1](https://reviewable.io/reviews/powershell/xbitlocker/16#-LDqRSM6DeZ6x63ujk0R:-LDqmEB8-LxqSFRcrRe_:b-896fix) ([raw file](https://github.com/powershell/xbitlocker/blob/7b9221386955463266f74e4d784aafd52fb37e04/Tests/Unit/xBitlockerCommon.tests.ps1#L30)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

You can remove this row.
</blockquote></details>

Done.

---

*[Tests/Unit/xBitlockerCommon.tests.ps1, line 42 at r1](https://reviewable.io/reviews/powershell/xbitlocker/16#-LDqRbZWC8PWZx2vtfrl:-LDqmFXBAGJjDDNeuC5K:b-896fix) ([raw file](https://github.com/powershell/xbitlocker/blob/7b9221386955463266f74e4d784aafd52fb37e04/Tests/Unit/xBitlockerCommon.tests.ps1#L42)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

You can remove this row.
</blockquote></details>

Done.

---

*[Tests/Unit/xBitlockerCommon.tests.ps1, line 79 at r1](https://reviewable.io/reviews/powershell/xbitlocker/16#-LDqVjrn4Y39ph9SnYXf:-LDqmJ-F1afJy23J01tq:b-896fix) ([raw file](https://github.com/powershell/xbitlocker/blob/7b9221386955463266f74e4d784aafd52fb37e04/Tests/Unit/xBitlockerCommon.tests.ps1#L79)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We can move the param block inside `Get-BitlockerVolume` so that you only need to specify that once.
Suggest changing to this so we align with the style guideline.

```
function Get-BitlockerVolume
{
    param
    (
        [Parameter()]
        [System.String]
        $MountPoint
    )
 }
```
</blockquote></details>

Done.

---

*[Tests/Unit/xBitlockerCommon.tests.ps1, line 111 at r1](https://reviewable.io/reviews/powershell/xbitlocker/16#-LDqWJfCDFVNgNkxP4dC:-LDqmLHA-m03tAHyb0dQ:b-896fix) ([raw file](https://github.com/powershell/xbitlocker/blob/7b9221386955463266f74e4d784aafd52fb37e04/Tests/Unit/xBitlockerCommon.tests.ps1#L111)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Remove this, see previous comment.
</blockquote></details>

Done.

---

*[Tests/Unit/xBitlockerCommon.tests.ps1, line 144 at r1](https://reviewable.io/reviews/powershell/xbitlocker/16#-LDqWMAN7eCESavsC-Ad:-LDqmNfeBcfsPCXHdZ6M:b-896fix) ([raw file](https://github.com/powershell/xbitlocker/blob/7b9221386955463266f74e4d784aafd52fb37e04/Tests/Unit/xBitlockerCommon.tests.ps1#L144)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Remove this, see previous comment.
</blockquote></details>

Done.

---

*[Tests/Unit/xBitlockerCommon.tests.ps1, line 176 at r1](https://reviewable.io/reviews/powershell/xbitlocker/16#-LDqUlLB4N4RhG5htuHl:-LDqmOCE3AQ40-zMf_5-:b-896fix) ([raw file](https://github.com/powershell/xbitlocker/blob/7b9221386955463266f74e4d784aafd52fb37e04/Tests/Unit/xBitlockerCommon.tests.ps1#L176)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please uncomment this, or remove if the function was not used. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/16)*

**Comment by johlju** [comment]
Just two tiny changes then I think this is good to go. 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[Tests/Unit/xBitlockerCommon.tests.ps1, line 9 at r2](https://reviewable.io/reviews/powershell/xbitlocker/16#-LDqrR01-mv6k4p_Y9pG:-LDqrR01-mv6k4p_Y9pH:b-nea8ku) ([raw file](https://github.com/powershell/xbitlocker/blob/2d90f38c3487dd6c1f8b841c2946c8dbbb51852f/Tests/Unit/xBitlockerCommon.tests.ps1#L9)):*
> ```PowerShell
>     InModuleScope "xBitlockerCommon" {
> 
>         function Get-BitlockerVolume {
> ```

We should have this open brace on a separate row. 

*That style guideline does not apply to InModuleScope-, Describe, Context-, It-blocks because how Pester is built. For Pester commands the open brace needs to be on the same row.*

---

*[Tests/Unit/xBitlockerCommon.tests.ps1, line 72 at r2](https://reviewable.io/reviews/powershell/xbitlocker/16#-LDqs5016b8Yyz-PkBqK:-LDqs5016b8Yyz-PkBqL:b-lnjt7w) ([raw file](https://github.com/powershell/xbitlocker/blob/2d90f38c3487dd6c1f8b841c2946c8dbbb51852f/Tests/Unit/xBitlockerCommon.tests.ps1#L72)):*
> ```PowerShell
>                 }
>             }
>             Context 'When OS Volume is Decrypted, but has TPM and Recovery Password Protectors assigned' {
> ```

Could we add a blank row before this one to, to be consequent? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/16#-:-LDqsEtE5_ctVVScksp6:bjxvha6)*

**Comment by MartinVokurek** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests/Unit/xBitlockerCommon.tests.ps1, line 9 at r2](https://reviewable.io/reviews/powershell/xbitlocker/16#-LDqrR01-mv6k4p_Y9pG:-LDqx4zo2aFW2IQXGYRA:b-896fix) ([raw file](https://github.com/powershell/xbitlocker/blob/2d90f38c3487dd6c1f8b841c2946c8dbbb51852f/Tests/Unit/xBitlockerCommon.tests.ps1#L9)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should have this open brace on a separate row. 

*That style guideline does not apply to InModuleScope-, Describe, Context-, It-blocks because how Pester is built. For Pester commands the open brace needs to be on the same row.*
</blockquote></details>

Done.

---

*[Tests/Unit/xBitlockerCommon.tests.ps1, line 72 at r2](https://reviewable.io/reviews/powershell/xbitlocker/16#-LDqs5016b8Yyz-PkBqK:-LDqxD2d3FaK9ZTI9TSW:b-896fix) ([raw file](https://github.com/powershell/xbitlocker/blob/2d90f38c3487dd6c1f8b841c2946c8dbbb51852f/Tests/Unit/xBitlockerCommon.tests.ps1#L72)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Could we add a blank row before this one to, to be consequent? 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/16)*

**Comment by johlju** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/16#-:-LDr27s5AAuLuYr614La:bnfp4nl)*

**Pull request merged**
