### PR TITLE
Added Windows "Client" OS support. Fixes #47

### LINKED ISSUE #47: Resource do not work on Windows 10
Due to this function [Assert-HasPrereqsForBitlocker](https://github.com/PowerShell/xBitlocker/blob/dev/Misc/xBitlockerCommon.psm1#L784) the resource doesn't start on the Windows 10. If you perform all the steps manually it works perfectly. 

Since Get-WindowsFeature doesn't exists on client OS the function throw 

> 'Required Bitlocker features need to be installed before xBitlocker can be used'

 which is not true for Pro, Enterprise, and Education editions of Windows 10.

`if(
((Get-CimInstance -ClassName Win32_OperatingSystem).ProductType -eq 1) -and 
(get-command enable-bitlocker -ErrorAction SilentlyContinue))
then {It is a workstation with BitLocker available, don't throw}`

Little check like that one could help you to avoid false negative assert.

Regards,
Viktor Frelikh

### PR DESCRIPTION
**Pull request by mnothh**
#### Pull Request (PR) description
Added support for Windows "Client" operating systems in the 
Assert-HasPrereqsForBitlocker function.

#### This Pull Request (PR) fixes the following issues
-Fixes #47 

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/48)

### CODE REVIEW

**Comment by mhendric** [comment]
Hi @mnothh , thanks for the submission. And sorry for the late response, as I've been on vacation. I'll get this code reviewed ASAP.

**Comment by mhendric** [comment]
> ```
>     {
>         $blFeature = Get-WindowsOptionalFeature BitLocker
>         if ($blFeature.InstallState -ne 'Installed')
>         {
> ```

Hi @mnothh, what specific Windows and PowerShell version did you test this on? This doesn't work on my Win10 machine. I have to add -Online and -FeatureName, and also need to look at the .State property, not the .InstallState property.

```
PS D:\> $blFeature = Get-WindowsOptionalFeature BitLocker
Get-WindowsOptionalFeature : A positional parameter cannot be found that accepts argument 'BitLocker'.
At line:1 char:14
+ $blFeature = Get-WindowsOptionalFeature BitLocker
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-WindowsOptionalFeature], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.Dism.Commands.GetWindowsOptionalFeatureCommand
```

Here's it working:

```
PS D:\> $blFeature = Get-WindowsOptionalFeature -Online -FeatureName BitLocker
PS D:\> $blFeature |fl


FeatureName      : BitLocker
DisplayName      : BitLocker Drive Encryption
Description      : Provides full volume disk encryption for both boot volumes and data volumes.
RestartRequired  : Possible
State            : Enabled
CustomProperties :
                   mum2:Version\Major : 8
                   mum2:Version\Minor : 0
                   ServerComponent\Description : BitLocker Drive Encryption helps to protect data on lost, stolen, or
                   inappropriately decommissioned computers by encrypting the entire volume and checking the integrity
                   of early boot components. Data is only decrypted if those components are successfully verified and
                   the encrypted drive is located in the original computer. Integrity checking requires a compatible
                   Trusted Platform Module (TPM).
                   ServerComponent\DisplayName : BitLocker Drive Encryption
                   ServerComponent\Id : 61
                   ServerComponent\Type : Feature
                   ServerComponent\UniqueName : BitLocker
                   ServerComponent\NonAncestorDependencies\ServerComponent\UniqueName : EnhancedStorage
                   ServerComponent\Deploys\Update\Name : BitLocker




PS D:\> $blFeature.InstallState
PS D:\> $blFeature.State
Enabled

PS D:\>     Get-ComputerInfo -Property @(
>>         'OsName',
>>         'OsOperatingSystemSKU',
>>         'OSArchitecture',
>>         'WindowsVersion',
>>         'WindowsBuildLabEx',
>>         'OsLanguage',
>>         'OsMuiLanguages')


OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1903
WindowsBuildLabEx    : 18362.1.amd64fre.19h1_release.190318-1202
OsLanguage           : en-US
OsMuiLanguages       : {en-US}



PS D:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by mnothh** [comment]
Hey @mhendric. You are likely correct.  I believe this was tested on 1709(off the top of my head).  I'm currently out of office as well.  As soon as I have access to my test machines I'll rework this to confirm it is compatible with newer releases as well.

**Comment by mnothh** [comment]
Hello @mhendric,

Sorry, finally got around to looking at this again.  It appears the test you ran was with an old commit(probably 1fb8d1564533af5cf12af1733c6bb4f789eadac6).  You should see that I later updated the pull request/branch with an additional commit(1cf4da15c8e132d2c273990c31ceb617720d1352).  That newest commit addresses exactly the issue and code change you mentioned.

Do I need to recreate the pull request or is this sufficient? 

Thanks!
-Mike

**Pull request closed without merging**
