### PR TITLE
xBitlockerCommon: Add remaining Unit tests for xBitlockerCommon

### LINKED ISSUE #6: xBitlockerCommon.psm1 does not handle Enabling AutoUnlock on existing volumes
The code in lines 234-238 of /Misc/xBitlockerCommon.psm1 which enables BitLocker AutoUnlock is only reached in the process of enabling BitLocker on a new volume.

If it encounters a BitLocker volume which already exists, no action is taken and the following is logged in the verbose output

> [[xBLAutoBitlocker]AutoBitlocker] AutoUnlock is not enabled for MountPoint: \?\Volume{guid}\

It would be more useful for ongoing configs if the setting could be re-applied or toggled.

### PR DESCRIPTION
**Pull request by mhendric**
#### Pull Request (PR) description
Fixes issue where AutoUnlock is not set if requested, if the disk was originally encrypted and AutoUnlock was not used. Also adds remaining Unit Tests for xBitlockerCommon.

#### What does this fix
- Fixes #6 

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/28)

### CODE REVIEW

**Review by athaynes — COMMENTED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/28)* status: 5 of 6 files reviewed, 9 unresolved discussions (waiting on @mhendric)

___
*[DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1, line 298 at r1](https://reviewable.io/reviews/powershell/xbitlocker/28#-LQeZ7rr0-kx6RQi5SAz:-LQeZ7rr0-kx6RQi5SB-:b6sjn8x) ([raw file](https://github.com/powershell/xbitlocker/blob/484c24298d4ff3dcfaf973b796970b6003ca7f76/DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1#L298)):*
> ```PowerShell
>     param
>     (
>         [parameter(Mandatory = $true)]
> ```

Parameter and the rest of these do not have the parameter decoration. There is ton of white space here, so check all of your functions. 
___
*[Misc/xBitlockerCommon.psm1, line 814 at r1](https://reviewable.io/reviews/powershell/xbitlocker/28#-LQeVJHx-zuZbt-atz04:-LQeVJHx-zuZbt-atz05:bp0bl7x) ([raw file](https://github.com/powershell/xbitlocker/blob/484c24298d4ff3dcfaf973b796970b6003ca7f76/Misc/xBitlockerCommon.psm1#L814)):*
> ```PowerShell
>     (
>         [Parameter(Mandatory = $true)]
>         $PSBoundParametersIn,
> ```

Needs a type.
___
*[Misc/xBitlockerCommon.psm1, line 860 at r1](https://reviewable.io/reviews/powershell/xbitlocker/28#-LQeVS9l7SkcbpJ2xyqK:-LQeVS9m-1lLFube0zJL:b18vpaa) ([raw file](https://github.com/powershell/xbitlocker/blob/484c24298d4ff3dcfaf973b796970b6003ca7f76/Misc/xBitlockerCommon.psm1#L860)):*
> ```PowerShell
>     (
>         [Parameter(Mandatory = $true)]
>         $PSBoundParametersIn,
> ```

Needs type
___
*[Misc/xBitlockerCommon.psm1, line 873 at r1](https://reviewable.io/reviews/powershell/xbitlocker/28#-LQeVass2zAglQiw5mnG:-LQeVass2zAglQiw5mnH:b-va7xw9) ([raw file](https://github.com/powershell/xbitlocker/blob/484c24298d4ff3dcfaf973b796970b6003ca7f76/Misc/xBitlockerCommon.psm1#L873)):*
> ```PowerShell
>     if ($ParamsToKeep.Count -gt 0 -and $ParamsToRemove.Count -gt 0)
>     {
>         throw 'Remove-FromPSBoundParametersUsingHashtable does not support using both ParamsToKeep and ParamsToRemove'
> ```

Can you add a parameter set to the function and let PS do this work for you?
___
*[Misc/xBitlockerCommon.psm1, line 880 at r1](https://reviewable.io/reviews/powershell/xbitlocker/28#-LQeWgyjCapm01WlJ0Zi:-LQeWgyjCapm01WlJ0Zj:b-qg57kv) ([raw file](https://github.com/powershell/xbitlocker/blob/484c24298d4ff3dcfaf973b796970b6003ca7f76/Misc/xBitlockerCommon.psm1#L880)):*
> ```PowerShell
>         $ParamsToKeep = $ParamsToKeep.ToLower()
> 
>         $lowerParamsToKeep = Convert-StringArrayToLowerCase -Array $ParamsToKeep
> ```

You can let PS do this for you with $lowerParamsToKeep = $lowerParamsToKeep.ToLower()
___
*[Misc/xBitlockerCommon.psm1, line 895 at r1](https://reviewable.io/reviews/powershell/xbitlocker/28#-LQeVtOx7AM5LqFIPI19:-LQeVtOx7AM5LqFIPI1A:b-jn4epn) ([raw file](https://github.com/powershell/xbitlocker/blob/484c24298d4ff3dcfaf973b796970b6003ca7f76/Misc/xBitlockerCommon.psm1#L895)):*
> ```PowerShell
>         foreach ($param in $ParamsToRemove)
>         {
>             $PSBoundParametersIn.Remove($param) | Out-Null
> ```

not a big deal, but you can use $null = so that you don't need to setup a pipeline to output to null. small perf improvements add up over time. 
___
*[Tests/Unit/xBitlockerCommon.tests.ps1, line 121 at r1](https://reviewable.io/reviews/powershell/xbitlocker/28#-LQeWtYYBk0qjEshl9-l:-LQeWtYYBk0qjEshl9-m:bsdifgn) ([raw file](https://github.com/powershell/xbitlocker/blob/484c24298d4ff3dcfaf973b796970b6003ca7f76/Tests/Unit/xBitlockerCommon.tests.ps1#L121)):*
> ```PowerShell
> 
>                     TestBitlocker -MountPoint 'C:' -PrimaryProtector 'TpmProtector' | Should -Be $false
>                 }   
> ```

lot of trailing spaces in this file.
___
*[Tests/Unit/xBitlockerCommon.tests.ps1, line 542 at r1](https://reviewable.io/reviews/powershell/xbitlocker/28#-LQeXnXk6DiWgWYRdF-W:-LQeXnXk6DiWgWYRdF-X:bjvufhd) ([raw file](https://github.com/powershell/xbitlocker/blob/484c24298d4ff3dcfaf973b796970b6003ca7f76/Tests/Unit/xBitlockerCommon.tests.ps1#L542)):*
> ```PowerShell
>             Context 'When EnableBitlocker is called, the volume is not yet encrypted, and Enable-Bitlocker does not return a result' {
>                 It 'Should throw an exception' {
>                     Mock -CommandName Get-BitLockerVolume -Verifiable -MockWith { return $decryptedOSBLV }
> ```

You should be able to use the module param in the mock so that you don't have to have the empty functions at the top. 
___
*[Tests/Unit/xBitlockerCommon.tests.ps1, line 733 at r1](https://reviewable.io/reviews/powershell/xbitlocker/28#-LQeYR6I-Ljny9D1Cnrm:-LQeYR6I-Ljny9D1Cnrn:b5s52s) ([raw file](https://github.com/powershell/xbitlocker/blob/484c24298d4ff3dcfaf973b796970b6003ca7f76/Tests/Unit/xBitlockerCommon.tests.ps1#L733)):*
> ```PowerShell
>         }
> 
>         <#
> ```

dead code should be removed

**Review by mhendric — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/28)* status: 5 of 6 files reviewed, 9 unresolved discussions (waiting on @athaynes)

___
*[DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1, line 298 at r1](https://reviewable.io/reviews/powershell/xbitlocker/28#-LQeZ7rr0-kx6RQi5SAz:-LQeceEH9fH0Fo72Hl44:b-2s1ev8) ([raw file](https://github.com/powershell/xbitlocker/blob/484c24298d4ff3dcfaf973b796970b6003ca7f76/DSCResources/MSFT_xBLAutoBitlocker/MSFT_xBLAutoBitlocker.psm1#L298)):*
<details><summary><i>Previously, athaynes (Adam Haynes) wrote…</i></summary><blockquote>

Parameter and the rest of these do not have the parameter decoration. There is ton of white space here, so check all of your functions. 
</blockquote></details>

This is fixed in https://github.com/PowerShell/xBitlocker/pull/27, as is unnecessary whitespace throughout the module.
___
*[Misc/xBitlockerCommon.psm1, line 814 at r1](https://reviewable.io/reviews/powershell/xbitlocker/28#-LQeVJHx-zuZbt-atz04:-LQedMfC2Zn089TmSxQ1:b-u84g41) ([raw file](https://github.com/powershell/xbitlocker/blob/484c24298d4ff3dcfaf973b796970b6003ca7f76/Misc/xBitlockerCommon.psm1#L814)):*
<details><summary><i>Previously, athaynes (Adam Haynes) wrote…</i></summary><blockquote>

Needs a type.
</blockquote></details>

Agreed. Although I've tried setting the type to System.Collection.Hashtable (which PSBoundParameters is), and for some reason it prevents modifications of the original item (almost like it's getting passed by Value instead of by Reference). I will try with System.Object and see if it behaves better.
___
*[Misc/xBitlockerCommon.psm1, line 860 at r1](https://reviewable.io/reviews/powershell/xbitlocker/28#-LQeVS9l7SkcbpJ2xyqK:-LQedmvw1YdvSZaNgW8u:b-u84g41) ([raw file](https://github.com/powershell/xbitlocker/blob/484c24298d4ff3dcfaf973b796970b6003ca7f76/Misc/xBitlockerCommon.psm1#L860)):*
<details><summary><i>Previously, athaynes (Adam Haynes) wrote…</i></summary><blockquote>

Needs type
</blockquote></details>

Agreed. Although I've tried setting the type to System.Collection.Hashtable (which PSBoundParameters is), and for some reason it prevents modifications of the original item (almost like it's getting passed by Value instead of by Reference). I will try with System.Object and see if it behaves better.
___
*[Misc/xBitlockerCommon.psm1, line 873 at r1](https://reviewable.io/reviews/powershell/xbitlocker/28#-LQeVass2zAglQiw5mnG:-LQee4V79LQWYVHmivp2:bxj4tra) ([raw file](https://github.com/powershell/xbitlocker/blob/484c24298d4ff3dcfaf973b796970b6003ca7f76/Misc/xBitlockerCommon.psm1#L873)):*
<details><summary><i>Previously, athaynes (Adam Haynes) wrote…</i></summary><blockquote>

Can you add a parameter set to the function and let PS do this work for you?
</blockquote></details>

Good suggestion. I'll give it a try.
___
*[Misc/xBitlockerCommon.psm1, line 880 at r1](https://reviewable.io/reviews/powershell/xbitlocker/28#-LQeWgyjCapm01WlJ0Zi:-LQeeCCg1EottIB_Bfz7:bjj7w70) ([raw file](https://github.com/powershell/xbitlocker/blob/484c24298d4ff3dcfaf973b796970b6003ca7f76/Misc/xBitlockerCommon.psm1#L880)):*
<details><summary><i>Previously, athaynes (Adam Haynes) wrote…</i></summary><blockquote>

You can let PS do this for you with $lowerParamsToKeep = $lowerParamsToKeep.ToLower()
</blockquote></details>

Yes, that will be simpler. I'll get it updated.
___
*[Misc/xBitlockerCommon.psm1, line 895 at r1](https://reviewable.io/reviews/powershell/xbitlocker/28#-LQeVtOx7AM5LqFIPI19:-LQeeKJQ1uoWN1Cmx5Jh:b-lf72q) ([raw file](https://github.com/powershell/xbitlocker/blob/484c24298d4ff3dcfaf973b796970b6003ca7f76/Misc/xBitlockerCommon.psm1#L895)):*
<details><summary><i>Previously, athaynes (Adam Haynes) wrote…</i></summary><blockquote>

not a big deal, but you can use $null = so that you don't need to setup a pipeline to output to null. small perf improvements add up over time. 
</blockquote></details>

I'll give that a try. As long as it doesn't trigger the unused variables rule from the Script Analyzer...
___
*[Tests/Unit/xBitlockerCommon.tests.ps1, line 121 at r1](https://reviewable.io/reviews/powershell/xbitlocker/28#-LQeWtYYBk0qjEshl9-l:-LQeeU1s6oHyT2N5K8oO:b-rrnzkv) ([raw file](https://github.com/powershell/xbitlocker/blob/484c24298d4ff3dcfaf973b796970b6003ca7f76/Tests/Unit/xBitlockerCommon.tests.ps1#L121)):*
<details><summary><i>Previously, athaynes (Adam Haynes) wrote…</i></summary><blockquote>

lot of trailing spaces in this file.
</blockquote></details>

Should be fixed in https://github.com/PowerShell/xBitlocker/pull/27
___
*[Tests/Unit/xBitlockerCommon.tests.ps1, line 542 at r1](https://reviewable.io/reviews/powershell/xbitlocker/28#-LQeXnXk6DiWgWYRdF-W:-LQee_oZE939yKNZvTze:byxkgjr) ([raw file](https://github.com/powershell/xbitlocker/blob/484c24298d4ff3dcfaf973b796970b6003ca7f76/Tests/Unit/xBitlockerCommon.tests.ps1#L542)):*
<details><summary><i>Previously, athaynes (Adam Haynes) wrote…</i></summary><blockquote>

You should be able to use the module param in the mock so that you don't have to have the empty functions at the top. 
</blockquote></details>

In my experience, if the machine running the tests doesn't have the module installed with the function to Mock (in this case the Bitlocker module), Mock will fail. Mock only succeeds on functions that are visible at the time of the Mock. I'll give the -Module parameter a try though.
___
*[Tests/Unit/xBitlockerCommon.tests.ps1, line 733 at r1](https://reviewable.io/reviews/powershell/xbitlocker/28#-LQeYR6I-Ljny9D1Cnrm:-LQeeu1o2cxBgQL_VPL_:b-rrnzkv) ([raw file](https://github.com/powershell/xbitlocker/blob/484c24298d4ff3dcfaf973b796970b6003ca7f76/Tests/Unit/xBitlockerCommon.tests.ps1#L733)):*
<details><summary><i>Previously, athaynes (Adam Haynes) wrote…</i></summary><blockquote>

dead code should be removed
</blockquote></details>

Should be fixed in https://github.com/PowerShell/xBitlocker/pull/27

**Review by mhendric — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/28)* status: 3 of 6 files reviewed, 9 unresolved discussions (waiting on @athaynes)

___
*[Misc/xBitlockerCommon.psm1, line 814 at r1](https://reviewable.io/reviews/powershell/xbitlocker/28#-LQeVJHx-zuZbt-atz04:-LQf57KT7scoMxMDKysd:b-896fix) ([raw file](https://github.com/powershell/xbitlocker/blob/484c24298d4ff3dcfaf973b796970b6003ca7f76/Misc/xBitlockerCommon.psm1#L814)):*
<details><summary><i>Previously, mhendric (Mike Hendrickson) wrote…</i></summary><blockquote>

Agreed. Although I've tried setting the type to System.Collection.Hashtable (which PSBoundParameters is), and for some reason it prevents modifications of the original item (almost like it's getting passed by Value instead of by Reference). I will try with System.Object and see if it behaves better.
</blockquote></details>

Done.
___
*[Misc/xBitlockerCommon.psm1, line 860 at r1](https://reviewable.io/reviews/powershell/xbitlocker/28#-LQeVS9l7SkcbpJ2xyqK:-LQf5HsS9dseLF_mtelk:b-896fix) ([raw file](https://github.com/powershell/xbitlocker/blob/484c24298d4ff3dcfaf973b796970b6003ca7f76/Misc/xBitlockerCommon.psm1#L860)):*
<details><summary><i>Previously, mhendric (Mike Hendrickson) wrote…</i></summary><blockquote>

Agreed. Although I've tried setting the type to System.Collection.Hashtable (which PSBoundParameters is), and for some reason it prevents modifications of the original item (almost like it's getting passed by Value instead of by Reference). I will try with System.Object and see if it behaves better.
</blockquote></details>

Done.
___
*[Misc/xBitlockerCommon.psm1, line 873 at r1](https://reviewable.io/reviews/powershell/xbitlocker/28#-LQeVass2zAglQiw5mnG:-LQf5JMe5LWGmmiYgzQj:b-896fix) ([raw file](https://github.com/powershell/xbitlocker/blob/484c24298d4ff3dcfaf973b796970b6003ca7f76/Misc/xBitlockerCommon.psm1#L873)):*
<details><summary><i>Previously, mhendric (Mike Hendrickson) wrote…</i></summary><blockquote>

Good suggestion. I'll give it a try.
</blockquote></details>

Done.
___
*[Misc/xBitlockerCommon.psm1, line 880 at r1](https://reviewable.io/reviews/powershell/xbitlocker/28#-LQeWgyjCapm01WlJ0Zi:-LQf5Kd-Dn8QzRD1ttAH:b-896fix) ([raw file](https://github.com/powershell/xbitlocker/blob/484c24298d4ff3dcfaf973b796970b6003ca7f76/Misc/xBitlockerCommon.psm1#L880)):*
<details><summary><i>Previously, mhendric (Mike Hendrickson) wrote…</i></summary><blockquote>

Yes, that will be simpler. I'll get it updated.
</blockquote></details>

Done.
___
*[Misc/xBitlockerCommon.psm1, line 895 at r1](https://reviewable.io/reviews/powershell/xbitlocker/28#-LQeVtOx7AM5LqFIPI19:-LQf5Lk86NxQ5c0ae1-M:b-896fix) ([raw file](https://github.com/powershell/xbitlocker/blob/484c24298d4ff3dcfaf973b796970b6003ca7f76/Misc/xBitlockerCommon.psm1#L895)):*
<details><summary><i>Previously, mhendric (Mike Hendrickson) wrote…</i></summary><blockquote>

I'll give that a try. As long as it doesn't trigger the unused variables rule from the Script Analyzer...
</blockquote></details>

Done.
___
*[Tests/Unit/xBitlockerCommon.tests.ps1, line 542 at r1](https://reviewable.io/reviews/powershell/xbitlocker/28#-LQeXnXk6DiWgWYRdF-W:-LQf5RRS1y62YoTs2vwd:b-83kxlc) ([raw file](https://github.com/powershell/xbitlocker/blob/484c24298d4ff3dcfaf973b796970b6003ca7f76/Tests/Unit/xBitlockerCommon.tests.ps1#L542)):*
<details><summary><i>Previously, mhendric (Mike Hendrickson) wrote…</i></summary><blockquote>

In my experience, if the machine running the tests doesn't have the module installed with the function to Mock (in this case the Bitlocker module), Mock will fail. Mock only succeeds on functions that are visible at the time of the Mock. I'll give the -Module parameter a try though.
</blockquote></details>

I tried again, and I can't Mock a function unless Mock knows about the function. So I think we need to keep these empty function declarations in place in the Unit tests for cases where the test machine doesn't have the Bitlocker module. Let me know if you have an alternate suggestion though.

**Review by athaynes — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/28#-:-LQivqeOD2TrXW3jDX5R:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
