### PR TITLE
Fix 'UsedSpaceOnly, SkipHardwareTest, HardwareEncryption properties cannot be set to False'

### LINKED ISSUE #12: UsedSpaceOnly, SkipHardwareTest, HardwareEncryption properties cannot be set to False
When defining xBLBitlocker or xBLAutoBitlocker resources, UsedSpace, SkipHardwareTest or HardwareEncryption Boolean properties can be defined, but no matter if they are defined as $True or $False, they are always processed as $True during Enable-Bitlocker.
That is because the properties are tested for existence on lines 133-156 of BitlockerCommon.ps1. And if they exist, they are hardcoded to $true in $params hashtable

I'm not sure what was the original idea here, because I can see that Enable-Bitlocker defines these parameters as switches, therefore if present, they are assumed true. And the README says the parameters behave "the same as in Enable-Bitlocker"

However, for me personally, this is incorrect behavior of DSC resource, because the resource happily accepts e.g. UsedSpaceOnly=$false, yet it silently passes UsedSpaceOnly=$true to Enable-Bitlocker, creating possible significant security issue.

### PR DESCRIPTION
**Pull request by mhendric**
#### Pull Request (PR) description
Fixes issue where Switch parameters are passed to Enable-Bitlocker even if the corresponding DSC resource parameter was set to False.

#### This Pull Request (PR) fixes the following issues
- Fixes #12 

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/42)

### CODE REVIEW

**Comment by mhendric** [comment]
@MartinVokurek , can you give this a review and make sure it addresses the issue you opened (#12)?

**Comment by MartinVokurek** [comment]
If I understand your fix correctly, you are removing any switch parameters set to False so that they don't get passed to e.g. Enable-Bitlocker. I am a little afraid that it's only partial solution. E.g. if I set HardwareEncryption=False, I expect the resource to ensure that only software encryption is used. But if the switch parameter gets filtered, the underlying Enable-Bitlocker cmdlet is left to use its default, which (IIRC) for HW encryption-capable drives is to use HW encryption. This is currently becoming an issue because of `https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/ADV180028`
I think that it might be necessary to ensure -HardwareEncryption:$false. Unfortunately, I don't have any HW encryption-capable drive handy to test now.

**Comment by mhendric** [comment]
Hey @MartinVokurek , thanks for looking this over. I wasn't aware that some switches, like HardwareEncryption, default to Enabled (if the hardware supports it). That being the case, just removing the switch won't be enough, as you pointed out. I'll take another crack at a fix for this and just address the root issue you pointed out in #12, where the EnableBitlocker helper function always passed $true for the switches if they are in PSBoundParameters.

**Comment by mhendric** [comment]
@MartinVokurek , I took another attempt at this. Can you give it a look? The changes to address your issue are in xBitlockerCommon.psm1 . Thanks.

**Review by MartinVokurek — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/xbitlocker/42#-:-LSPHsZqAy4RPS1fgUD3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
